CITIES = [
    "Nairobi",
    "Kitale",
    "Kisumu",
    "Machakos",
    "Nakuru",
    "Bungoma",
    "Naivasha",
    "Kakamega",
    "Webuye",
    "Iten",
    "Eldoret",
    "Thika",
    "Malaba",
    "Narok",
    "Kericho",
    "Kampala",
    "Jinja",
    "Busia",
    "Mbale",
    "Tororo",
    "Lwakhakha",
    "Suam",
    "Entebbe",
    "Siaya",
    "Eldama Ravine",
    "Bomet",
    "Ahero",
    "Muhoroni",
    "Butere",
    "Ugunja",
    "Chwele",
    "Iganga",
    "Bugiri",
    "Buwuni",
    "Nankoma",
    "Kapchorwa",
    "Kaliro",
    "Pallisa",
    "Bumala",
    "Sironko",
    "Maai Mahiu",
    "Ntulele",
    "Kisii",
    "Athi River",
    "Kapsabet",
    "Mogotio",
    "Marigat",
    "Tirinyi",
    "Namutumba",
    "Nyeri",
    "Murang'a",
    "Oyugis",
    "Rongo",
    "Mumias",
    "Nyamira",
    "Kimilili",
    "Cheptais",
    "Endebess",
    "Kiminini",
    "Mau Summit",
    "Londiani Junction",
    "Timboroa",
    "GilGil",
    "Burnt Forest",
    "Cheptiret",
    "Chavakali",
    "Malava",
    "Uthiru",
    "Kimende",
    "Kinungi"
]

CITIES_TO_LABEL = {"Nairobi": "ORIGIN", "Kampala": "DESTINATION"}
