CITIES = [
    "Nairobi",
    "Kitale",
    "Kisumu",
    "Machakos",
    "Nakuru",
    "Bungoma",
    "Naivasha",
    "Kakamega",
    "Webuye",
    "Iten",
    "Eldoret",
    "Thika",
    "Malaba",
    "Narok",
    "Kericho",
    "Kampala",
    "Jinja",
    "Busia",
    "Mbale",
    "Tororo",
    "Lwakhakha",
    "Suam",
    "Entebbe",
    "Siaya",
    "Eldama Ravine",
    "Bomet",
    "Ahero",
    "Muhoroni",
    "Butere",
    "Ugunja",
    "Chwele",
]

CITIES_TO_LABEL = {"Nairobi": "ORIGIN", "Kampala": "DESTINATION"}
